# Generated by Django 5.1.7 on 2026-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingpoint',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
