# Generated by Django 5.1.4 on 2025-01-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_station", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingpoint",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chargingpoint",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
