# Generated by Django 5.1.4 on 2025-01-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_station", "0002_chargingpoint_latitude_chargingpoint_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingpoint",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
