# Generated by Django 5.1.7 on 2026-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0002_alter_chargingpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingpoint',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
