# Generated by Django 5.1.7 on 2026-04-20 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0003_chargingpoint_last_synced_at_chargingpoint_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='amenities',
            field=models.JSONField(blank=True, help_text="e.g. ['coffee shop', 'mall', 'restrooms']", null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='booking_url',
            field=models.URLField(blank=True, help_text="Owner's own booking page used for redirect model", null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='charging_speed_kw',
            field=models.PositiveIntegerField(blank=True, help_text='Max charging speed in kW', null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='connector_types',
            field=models.JSONField(blank=True, help_text="e.g. ['CCS2', 'Type2']", null=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='photos',
            field=models.JSONField(blank=True, help_text='List of uploaded photo URLs', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='connector_type',
            field=models.CharField(blank=True, choices=[('ccs2', 'CCS2'), ('chademo', 'CHAdeMO'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('tesla', 'Tesla'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StationOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('business_reg_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='owner_logos/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='owner_docs/')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending review'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('savings', 'Savings'), ('transmission', 'Transmission')], max_length=20, null=True)),
                ('account_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('payfast_merchant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payfast_merchant_key', models.CharField(blank=True, max_length=100, null=True)),
                ('banking_verified', models.BooleanField(default=False)),
                ('banking_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payout_schedule', models.CharField(choices=[('weekly', 'Weekly (every Monday)'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_referral_clicks', models.PositiveIntegerField(default=0)),
                ('listing_tier', models.CharField(choices=[('free', 'Free'), ('featured', 'Featured'), ('premium', 'Premium')], default='free', max_length=20)),
                ('tier_expires_at', models.DateTimeField(blank=True, null=True)),
                ('popia_consent', models.BooleanField(default=False)),
                ('popia_consent_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('banking_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('banking_details_updated_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_bookings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bookings', models.ManyToManyField(blank=True, related_name='payout', to='charging_station.booking')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='charging_station.stationownerprofile')),
            ],
        ),
    ]
