# Generated by Django 5.1.4 on 2025-01-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='status',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
