# Generated by Django 5.1.4 on 2025-01-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0006_chargingsession_status_delete_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingsession',
            name='status',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Scheduled', max_length=100, null=True),
        ),
    ]
