# Generated by Django 5.1.4 on 2025-01-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0008_chargingpoint_off_peak_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingsession',
            name='cost',
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chargingpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Confirmed', max_length=100),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('costs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charging_station.chargingpoint')),
            ],
        ),
    ]
