# Generated by Django 5.1.4 on 2025-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0010_booking_user_alter_booking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingpoint',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
