# Generated by Django 5.1.4 on 2025-01-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0011_alter_chargingpoint_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingpoint',
            name='availability',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
