# Generated by Django 5.1.4 on 2025-02-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_station", "0015_profile_location_paymentmethods"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="charging_station.paymentmethods",
            ),
        ),
    ]
