# Generated by Django 5.1.4 on 2025-02-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charging_station", "0019_alter_chargingpoint_location"),
    ]

    operations = []
