# Generated by Django 5.1.4 on 2025-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_station", "0020_auto_20250228_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsession",
            name="location",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
