# Generated by Django 5.1.7 on 2025-05-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0028_subscriptionplan_chargingstationanalitics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
