# Generated by Django 5.1.7 on 2025-06-05 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0030_alter_comment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
