# Generated by Django 5.1.7 on 2025-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0031_rename_payment_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
