# Generated by Django 5.1.7 on 2025-06-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0033_booking_duration_alter_booking_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
    ]
