# Generated by Django 5.1.7 on 2025-06-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0034_remove_booking_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='costs',
        ),
    ]
