# Generated by Django 5.1.7 on 2025-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0036_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=1000),
        ),
    ]
