# Generated by Django 5.1.7 on 2025-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0040_chargingpoint_address_chargingpoint_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingpoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargingpoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
