# Generated by Django 5.1.7 on 2025-12-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0047_alter_profile_profile_picture'),
    ]

    operations = [
    ]
