# Generated by Django 5.1.7 on 2026-01-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0048_add_comment_parent_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingpoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='chargingpoint',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
