# Generated by Django 5.1.7 on 2026-01-25 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0049_remove_chargingpoint_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(default='platform', max_length=50),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='chargingpoint',
            name='status',
            field=models.CharField(choices=[('info_only', 'Info Only'), ('claimed', 'Claimed'), ('bookable', 'Bookable')], default='info_only', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='station_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='chargingpoint',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
