# Generated by Django 5.1.7 on 2026-02-10 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_location_if_exists(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
            ["charging_station_chargingsession", "location"],
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE charging_station_chargingsession DROP COLUMN location")


def add_location_back(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
            ["charging_station_chargingsession", "location"],
        )
        if not cursor.fetchone()[0]:
            cursor.execute(
                "ALTER TABLE charging_station_chargingsession "
                "ADD COLUMN location varchar(150) NULL"
            )


def create_booking_unique_if_missing(apps, schema_editor):
    from django.db import connection

    table = "charging_station_booking"
    wanted = "user_id,station_id,start_time,end_time"
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) as cols "
            "FROM information_schema.STATISTICS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s "
            "GROUP BY INDEX_NAME HAVING cols = %s",
            [table, wanted],
        )
        if not cursor.fetchone():
            cursor.execute(
                "ALTER TABLE charging_station_booking "
                "ADD UNIQUE INDEX uniq_booking_user_station_start_end (user_id, station_id, start_time, end_time)"
            )


def drop_booking_unique_if_exists(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.STATISTICS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s",
            ["charging_station_booking", "uniq_booking_user_station_start_end"],
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE charging_station_booking DROP INDEX uniq_booking_user_station_start_end")


def create_rating_unique_if_missing(apps, schema_editor):
    from django.db import connection

    table = "charging_station_rating"
    wanted = "user_id,station_id"
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) as cols "
            "FROM information_schema.STATISTICS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s "
            "GROUP BY INDEX_NAME HAVING cols = %s",
            [table, wanted],
        )
        if not cursor.fetchone():
            cursor.execute(
                "ALTER TABLE charging_station_rating "
                "ADD UNIQUE INDEX uniq_rating_user_station (user_id, station_id)"
            )


def drop_rating_unique_if_exists(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.STATISTICS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s",
            ["charging_station_rating", "uniq_rating_user_station"],
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE charging_station_rating DROP INDEX uniq_rating_user_station")


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0052_alter_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_location_if_exists, add_location_back),
        # The following AddField operations were removed because the columns
        # already exist in the database. Keeping them would raise duplicate
        # column errors on MySQL. If your DB lacks any of these columns,
        # re-add the corresponding migration or run the appropriate SQL.
        migrations.RunPython(create_booking_unique_if_missing, drop_booking_unique_if_exists),
        migrations.RunPython(create_rating_unique_if_missing, drop_rating_unique_if_exists),
    ]
