# Generated by Django 5.1.7 on 2026-02-10 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_location_if_exists(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
            ["charging_station_chargingsession", "location"],
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE charging_station_chargingsession DROP COLUMN location")


def add_location_back(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
            ["charging_station_chargingsession", "location"],
        )
        if not cursor.fetchone()[0]:
            cursor.execute(
                "ALTER TABLE charging_station_chargingsession "
                "ADD COLUMN location varchar(150) NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0053_remove_chargingsession_location_booking_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_location_if_exists, add_location_back),
        # Note: AddField operations were removed because the columns already
        # exist in the database; attempting to create them caused duplicate
        # column errors on MySQL.
    ]
