# Generated by Django 5.1.7 on 2026-01-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.TextField(blank=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
