# Generated by Django 5.1.7 on 2026-01-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_shopifystore'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
