# Generated by Django 5.1.7 on 2026-01-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_product_shopify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_station_owner',
            field=models.BooleanField(default=False, help_text='Can this user manage charging stations?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_station_owner_verified',
            field=models.BooleanField(default=False, help_text='Admin verified station owner'),
        ),
    ]
