# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38ad53418398cc5f23f5050090fcef5e"
name = "VoltHub"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
